import type { Metadata } from "next";
import { Inter, ABeeZee } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Footer } from "@/components";

const inter = ABeeZee({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={clsx(
        inter.className,
        "items-center min-h-screen flex flex-col justify-between"
      )}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
